/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const LoveMessage = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
});
export const MemoryItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addLoveMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addMemory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllLoveMessages' : IDL.Func([], [IDL.Vec(LoveMessage)], ['query']),
  'getAllMemories' : IDL.Func([], [IDL.Vec(MemoryItem)], ['query']),
  'getLoveMessage' : IDL.Func([IDL.Text], [LoveMessage], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const LoveMessage = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
  });
  const MemoryItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addLoveMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addMemory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllLoveMessages' : IDL.Func([], [IDL.Vec(LoveMessage)], ['query']),
    'getAllMemories' : IDL.Func([], [IDL.Vec(MemoryItem)], ['query']),
    'getLoveMessage' : IDL.Func([IDL.Text], [LoveMessage], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };